"""added type for request table

Revision ID: 444aa1aa7840
Revises: 984bd598f713
Create Date: 2023-12-21 13:15:59.837805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444aa1aa7840'
down_revision: Union[str, None] = '984bd598f713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('type', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'type')
    # ### end Alembic commands ###
