"""Added activate column

Revision ID: 52f496716ac8
Revises: 9d68cca49125
Create Date: 2024-01-02 07:19:27.764681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f496716ac8'
down_revision: Union[str, None] = '9d68cca49125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_settings', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_settings', 'active')
    # ### end Alembic commands ###
