"""Init migration

Revision ID: 73f1d5f84e4b
Revises: 
Create Date: 2023-12-21 11:18:54.735685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73f1d5f84e4b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'tmdb_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('requests', 'date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('requests', 'status',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'privilege',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'privilege',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('requests', 'status',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('requests', 'date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('requests', 'tmdb_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
