"""Changed chat_id for int

Revision ID: a5fed46443dd
Revises: 444aa1aa7840
Create Date: 2024-01-02 06:27:32.305052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5fed46443dd'
down_revision: Union[str, None] = '444aa1aa7840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_settings', sa.Column('bot_id', sa.String(), nullable=True))
    op.alter_column('telegram_settings', 'chat_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint('telegram_settings_user_id_fkey', 'telegram_settings', type_='foreignkey')
    op.drop_column('telegram_settings', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_settings', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('telegram_settings_user_id_fkey', 'telegram_settings', 'users', ['user_id'], ['id'])
    op.alter_column('telegram_settings', 'chat_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('telegram_settings', 'bot_id')
    # ### end Alembic commands ###
