"""Changed relation to one-to-one for telegram settings

Revision ID: b1feb62ce336
Revises: e963828a9bcc
Create Date: 2024-01-09 14:19:29.955347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1feb62ce336'
down_revision: Union[str, None] = 'e963828a9bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegram_settings', 'chat_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('telegram_settings', 'bot_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('telegram_settings', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegram_settings', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('telegram_settings', 'bot_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('telegram_settings', 'chat_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
